### ISSUE TITLE
Provide guidance on installation

### ISSUE THREAD

**Issue by tomkerkhove** [terrajobst/themesof.net#2]
Provide guidance on installation so we can run our own copy of this

**Comment by terrajobst** [comment]
I have given this some thought. I believe this site is turning into a very specialized tool for the .NET product planning. It's an internal tool, maintained by a single person, me. As such I'm not able to maintain a general purpose tool. Not because I don't believe in such a tool; but because I don't want to be limited in doing what's best for our needs.

**Comment by tomkerkhove** [comment]
No problem @terrajobst, I fully understand!
