### ISSUE TITLE
Support Azure DevOps Tags with filtering

### ISSUE THREAD

**Issue by marcpopMSFT** [terrajobst/themesof.net#7]
I added a Team:SDK tag to a work item to test and then filtered the view but the item was filtered out.  Note that the UI successfully shows the tag but just the filtering wasn't working. It'd be great if I could tag all of the items for my team as they live across 4 different repos/services and then filter out to just those items.

**Comment by terrajobst** [comment]
When you the filtering didn't work, what didn't work? I just tried it and it shows these items:

https://themesof.net/?q=is:open%20kinds:teu%20team:SDK

![image](https://user-images.githubusercontent.com/5169960/105261228-1d280d80-5b44-11eb-907b-e892ce5c4a69.png)

In general, the result will be a tree. If parents or children of a matched item themselves don't satisfy the filter they are still displayed, but are faded out. The intent there is so that you can look for a particular parent and still see their children.

**Comment by marcpopMSFT** [comment]
Sorry, missed your reply.  The filter doesn't work for ADO items like this one:
![image](https://user-images.githubusercontent.com/12663534/107317203-0f80ec00-6a4f-11eb-92aa-dc06f8809cd8.png)

**Comment by terrajobst** [comment]
Gotcha. That's probably a bug in how I expose the TFS work items to the standardized tree node. Will take a look.
